// Country detail metadata for the country popup, keyed by football-data team.tla (3-letter code).
//
// This data is NOT available from the football-data.org API, so it is maintained manually here.
// Values verified against official sources (FIFA Men's World Ranking 2026-06-11 edition;
// Wikipedia "[Country] at the FIFA World Cup" records; UN/World Bank population estimates).
//
// FIFA ranking and World Cup appearance counts change over time — they are a labeled SNAPSHOT
// (see FIFA_RANK_SNAPSHOT / WC_APPEARANCE_SNAPSHOT). Update the values here when refreshing.
// wcAppearances is the all-time finals count and INCLUDES 2026 for teams that qualified.

export interface CountryDetail {
  // World Cup
  confederation: string; // football confederation, e.g. "AFC", "UEFA"
  fifaRank: number; // FIFA ranking snapshot
  wcAppearances: number; // World Cup finals appearances, all-time (see WC_APPEARANCE_SNAPSHOT)
  bestResult: string; // best World Cup result (Korean display string)
  // Country basics
  continent: string; // geographic continent (Korean)
  capital: string; // capital city (Korean)
  population: string; // population (pre-formatted Korean display string)
  languages: string; // official language(s) (Korean)
}

// Labels shown in the popup so the time-sensitive figures are clearly dated.
export const FIFA_RANK_SNAPSHOT = "2026년 6월 기준";
export const WC_APPEARANCE_SNAPSHOT = "역대 통산";

// Uruguay appears under two codes (URU / URY) in the source data — share one record.
const URUGUAY: CountryDetail = {
  confederation: "CONMEBOL",
  fifaRank: 16,
  wcAppearances: 15,
  bestResult: "우승 (2회 · 1930, 1950)",
  continent: "남아메리카",
  capital: "몬테비데오",
  population: "약 350만",
  languages: "스페인어",
};

export const COUNTRY_DETAIL_BY_TLA: Record<string, CountryDetail> = {
  // ── AFC (아시아) ─────────────────────────────────────────────
  KOR: {
    confederation: "AFC",
    fifaRank: 25,
    wcAppearances: 12,
    bestResult: "4강 (2002)",
    continent: "아시아",
    capital: "서울",
    population: "약 5,170만",
    languages: "한국어",
  },
  JPN: {
    confederation: "AFC",
    fifaRank: 18,
    wcAppearances: 8,
    bestResult: "16강 (2002, 2010, 2018, 2022)",
    continent: "아시아",
    capital: "도쿄",
    population: "약 1억 2,400만",
    languages: "일본어",
  },
  AUS: {
    confederation: "AFC",
    fifaRank: 27,
    wcAppearances: 7,
    bestResult: "16강 (2006, 2022)",
    continent: "오세아니아",
    capital: "캔버라",
    population: "약 2,700만",
    languages: "영어",
  },
  IRN: {
    confederation: "AFC",
    fifaRank: 20,
    wcAppearances: 7,
    bestResult: "조별리그",
    continent: "아시아",
    capital: "테헤란",
    population: "약 9,100만",
    languages: "페르시아어",
  },
  KSA: {
    confederation: "AFC",
    fifaRank: 42,
    wcAppearances: 7,
    bestResult: "16강 (1994)",
    continent: "아시아",
    capital: "리야드",
    population: "약 3,700만",
    languages: "아랍어",
  },
  QAT: {
    confederation: "AFC",
    fifaRank: 56,
    wcAppearances: 2,
    bestResult: "조별리그",
    continent: "아시아",
    capital: "도하",
    population: "약 300만",
    languages: "아랍어",
  },
  UZB: {
    confederation: "AFC",
    fifaRank: 50,
    wcAppearances: 1,
    bestResult: "첫 본선 진출",
    continent: "아시아",
    capital: "타슈켄트",
    population: "약 3,600만",
    languages: "우즈베크어",
  },
  JOR: {
    confederation: "AFC",
    fifaRank: 63,
    wcAppearances: 1,
    bestResult: "첫 본선 진출",
    continent: "아시아",
    capital: "암만",
    population: "약 1,100만",
    languages: "아랍어",
  },
  IRQ: {
    confederation: "AFC",
    fifaRank: 57,
    wcAppearances: 2,
    bestResult: "조별리그 (1986)",
    continent: "아시아",
    capital: "바그다드",
    population: "약 4,800만",
    languages: "아랍어",
  },

  // ── CONCACAF (북중미) ────────────────────────────────────────
  USA: {
    confederation: "CONCACAF",
    fifaRank: 17,
    wcAppearances: 12,
    bestResult: "3위 (1930)",
    continent: "북아메리카",
    capital: "워싱턴 D.C.",
    population: "약 3억 4,000만",
    languages: "영어",
  },
  CAN: {
    confederation: "CONCACAF",
    fifaRank: 30,
    wcAppearances: 3,
    bestResult: "조별리그",
    continent: "북아메리카",
    capital: "오타와",
    population: "약 4,100만",
    languages: "영어 · 프랑스어",
  },
  MEX: {
    confederation: "CONCACAF",
    fifaRank: 14,
    wcAppearances: 18,
    bestResult: "8강 (1970, 1986)",
    continent: "북아메리카",
    capital: "멕시코시티",
    population: "약 1억 2,900만",
    languages: "스페인어",
  },
  CRC: {
    confederation: "CONCACAF",
    fifaRank: 53,
    wcAppearances: 6,
    bestResult: "8강 (2014)",
    continent: "북아메리카",
    capital: "산호세",
    population: "약 520만",
    languages: "스페인어",
  },
  PAN: {
    confederation: "CONCACAF",
    fifaRank: 34,
    wcAppearances: 2,
    bestResult: "조별리그 (2018)",
    continent: "북아메리카",
    capital: "파나마시티",
    population: "약 440만",
    languages: "스페인어",
  },
  HON: {
    confederation: "CONCACAF",
    fifaRank: 65,
    wcAppearances: 3,
    bestResult: "조별리그",
    continent: "북아메리카",
    capital: "테구시갈파",
    population: "약 1,050만",
    languages: "스페인어",
  },
  HAI: {
    confederation: "CONCACAF",
    fifaRank: 83,
    wcAppearances: 2,
    bestResult: "조별리그 (1974)",
    continent: "북아메리카",
    capital: "포르토프랭스",
    population: "약 1,200만",
    languages: "프랑스어 · 아이티 크레올어",
  },
  CUW: {
    confederation: "CONCACAF",
    fifaRank: 82,
    wcAppearances: 1,
    bestResult: "첫 본선 진출",
    continent: "북아메리카",
    capital: "빌렘스타트",
    population: "약 15만",
    languages: "네덜란드어 · 파피아멘토어",
  },

  // ── CONMEBOL (남미) ─────────────────────────────────────────
  BRA: {
    confederation: "CONMEBOL",
    fifaRank: 6,
    wcAppearances: 23,
    bestResult: "우승 (5회)",
    continent: "남아메리카",
    capital: "브라질리아",
    population: "약 2억 1,600만",
    languages: "포르투갈어",
  },
  ARG: {
    confederation: "CONMEBOL",
    fifaRank: 1,
    wcAppearances: 19,
    bestResult: "우승 (3회 · 1978, 1986, 2022)",
    continent: "남아메리카",
    capital: "부에노스아이레스",
    population: "약 4,600만",
    languages: "스페인어",
  },
  URU: URUGUAY,
  URY: URUGUAY,
  COL: {
    confederation: "CONMEBOL",
    fifaRank: 13,
    wcAppearances: 7,
    bestResult: "8강 (2014)",
    continent: "남아메리카",
    capital: "보고타",
    population: "약 5,200만",
    languages: "스페인어",
  },
  ECU: {
    confederation: "CONMEBOL",
    fifaRank: 23,
    wcAppearances: 5,
    bestResult: "16강 (2006)",
    continent: "남아메리카",
    capital: "키토",
    population: "약 1,800만",
    languages: "스페인어",
  },
  PAR: {
    confederation: "CONMEBOL",
    fifaRank: 41,
    wcAppearances: 9,
    bestResult: "8강 (2010)",
    continent: "남아메리카",
    capital: "아순시온",
    population: "약 690만",
    languages: "스페인어 · 과라니어",
  },
  CHI: {
    confederation: "CONMEBOL",
    fifaRank: 51,
    wcAppearances: 9,
    bestResult: "3위 (1962)",
    continent: "남아메리카",
    capital: "산티아고",
    population: "약 1,950만",
    languages: "스페인어",
  },
  PER: {
    confederation: "CONMEBOL",
    fifaRank: 52,
    wcAppearances: 5,
    bestResult: "8강 (1970)",
    continent: "남아메리카",
    capital: "리마",
    population: "약 3,400만",
    languages: "스페인어",
  },

  // ── UEFA (유럽) ─────────────────────────────────────────────
  ENG: {
    confederation: "UEFA",
    fifaRank: 4,
    wcAppearances: 17,
    bestResult: "우승 (1966)",
    continent: "유럽",
    capital: "런던",
    population: "약 5,700만",
    languages: "영어",
  },
  FRA: {
    confederation: "UEFA",
    fifaRank: 3,
    wcAppearances: 17,
    bestResult: "우승 (2회 · 1998, 2018)",
    continent: "유럽",
    capital: "파리",
    population: "약 6,800만",
    languages: "프랑스어",
  },
  ESP: {
    confederation: "UEFA",
    fifaRank: 2,
    wcAppearances: 17,
    bestResult: "우승 (2010)",
    continent: "유럽",
    capital: "마드리드",
    population: "약 4,800만",
    languages: "스페인어",
  },
  GER: {
    confederation: "UEFA",
    fifaRank: 10,
    wcAppearances: 21,
    bestResult: "우승 (4회)",
    continent: "유럽",
    capital: "베를린",
    population: "약 8,400만",
    languages: "독일어",
  },
  POR: {
    confederation: "UEFA",
    fifaRank: 5,
    wcAppearances: 9,
    bestResult: "3위 (1966)",
    continent: "유럽",
    capital: "리스본",
    population: "약 1,030만",
    languages: "포르투갈어",
  },
  NED: {
    confederation: "UEFA",
    fifaRank: 8,
    wcAppearances: 12,
    bestResult: "준우승 (3회)",
    continent: "유럽",
    capital: "암스테르담",
    population: "약 1,780만",
    languages: "네덜란드어",
  },
  ITA: {
    confederation: "UEFA",
    fifaRank: 12,
    wcAppearances: 18,
    bestResult: "우승 (4회)",
    continent: "유럽",
    capital: "로마",
    population: "약 5,890만",
    languages: "이탈리아어",
  },
  BEL: {
    confederation: "UEFA",
    fifaRank: 9,
    wcAppearances: 15,
    bestResult: "3위 (2018)",
    continent: "유럽",
    capital: "브뤼셀",
    population: "약 1,170만",
    languages: "네덜란드어 · 프랑스어 · 독일어",
  },
  CRO: {
    confederation: "UEFA",
    fifaRank: 11,
    wcAppearances: 7,
    bestResult: "준우승 (2018)",
    continent: "유럽",
    capital: "자그레브",
    population: "약 390만",
    languages: "크로아티아어",
  },
  SUI: {
    confederation: "UEFA",
    fifaRank: 19,
    wcAppearances: 13,
    bestResult: "8강 (1934, 1938, 1954)",
    continent: "유럽",
    capital: "베른",
    population: "약 880만",
    languages: "독일어 · 프랑스어 · 이탈리아어",
  },
  DEN: {
    confederation: "UEFA",
    fifaRank: 21,
    wcAppearances: 6,
    bestResult: "8강 (1998)",
    continent: "유럽",
    capital: "코펜하겐",
    population: "약 590만",
    languages: "덴마크어",
  },
  POL: {
    confederation: "UEFA",
    fifaRank: 36,
    wcAppearances: 9,
    bestResult: "3위 (1974, 1982)",
    continent: "유럽",
    capital: "바르샤바",
    population: "약 3,800만",
    languages: "폴란드어",
  },
  SRB: {
    confederation: "UEFA",
    fifaRank: 43,
    wcAppearances: 13,
    bestResult: "4강 (1930, 1962 · 유고슬라비아)",
    continent: "유럽",
    capital: "베오그라드",
    population: "약 660만",
    languages: "세르비아어",
  },
  AUT: {
    confederation: "UEFA",
    fifaRank: 24,
    wcAppearances: 8,
    bestResult: "3위 (1954)",
    continent: "유럽",
    capital: "빈",
    population: "약 920만",
    languages: "독일어",
  },
  SCO: {
    confederation: "UEFA",
    fifaRank: 42,
    wcAppearances: 9,
    bestResult: "조별리그",
    continent: "유럽",
    capital: "에든버러",
    population: "약 550만",
    languages: "영어 · 스코틀랜드 게일어",
  },
  WAL: {
    confederation: "UEFA",
    fifaRank: 37,
    wcAppearances: 2,
    bestResult: "8강 (1958)",
    continent: "유럽",
    capital: "카디프",
    population: "약 310만",
    languages: "영어 · 웨일스어",
  },
  TUR: {
    confederation: "UEFA",
    fifaRank: 22,
    wcAppearances: 3,
    bestResult: "3위 (2002)",
    continent: "유럽 · 아시아",
    capital: "앙카라",
    population: "약 8,500만",
    languages: "튀르키예어",
  },
  UKR: {
    confederation: "UEFA",
    fifaRank: 32,
    wcAppearances: 1,
    bestResult: "8강 (2006)",
    continent: "유럽",
    capital: "키이우",
    population: "약 3,800만",
    languages: "우크라이나어",
  },
  NOR: {
    confederation: "UEFA",
    fifaRank: 31,
    wcAppearances: 4,
    bestResult: "16강 (1998)",
    continent: "유럽",
    capital: "오슬로",
    population: "약 550만",
    languages: "노르웨이어",
  },
  SWE: {
    confederation: "UEFA",
    fifaRank: 38,
    wcAppearances: 13,
    bestResult: "준우승 (1958)",
    continent: "유럽",
    capital: "스톡홀름",
    population: "약 1,050만",
    languages: "스웨덴어",
  },
  CZE: {
    confederation: "UEFA",
    fifaRank: 40,
    wcAppearances: 10,
    bestResult: "준우승 (1934, 1962 · 체코슬로바키아)",
    continent: "유럽",
    capital: "프라하",
    population: "약 1,090만",
    languages: "체코어",
  },
  GRE: {
    confederation: "UEFA",
    fifaRank: 48,
    wcAppearances: 3,
    bestResult: "16강 (2014)",
    continent: "유럽",
    capital: "아테네",
    population: "약 1,030만",
    languages: "그리스어",
  },
  BIH: {
    confederation: "UEFA",
    fifaRank: 64,
    wcAppearances: 2,
    bestResult: "조별리그 (2014)",
    continent: "유럽",
    capital: "사라예보",
    population: "약 320만",
    languages: "보스니아어 · 세르비아어 · 크로아티아어",
  },

  // ── CAF (아프리카) ──────────────────────────────────────────
  MAR: {
    confederation: "CAF",
    fifaRank: 7,
    wcAppearances: 7,
    bestResult: "4강 (2022)",
    continent: "아프리카",
    capital: "라바트",
    population: "약 3,770만",
    languages: "아랍어 · 베르베르어",
  },
  SEN: {
    confederation: "CAF",
    fifaRank: 15,
    wcAppearances: 4,
    bestResult: "8강 (2002)",
    continent: "아프리카",
    capital: "다카르",
    population: "약 1,800만",
    languages: "프랑스어",
  },
  TUN: {
    confederation: "CAF",
    fifaRank: 45,
    wcAppearances: 7,
    bestResult: "조별리그",
    continent: "아프리카",
    capital: "튀니스",
    population: "약 1,230만",
    languages: "아랍어",
  },
  ALG: {
    confederation: "CAF",
    fifaRank: 28,
    wcAppearances: 5,
    bestResult: "16강 (2014)",
    continent: "아프리카",
    capital: "알제",
    population: "약 4,600만",
    languages: "아랍어 · 베르베르어",
  },
  EGY: {
    confederation: "CAF",
    fifaRank: 29,
    wcAppearances: 4,
    bestResult: "조별리그",
    continent: "아프리카",
    capital: "카이로",
    population: "약 1억 1,400만",
    languages: "아랍어",
  },
  NGA: {
    confederation: "CAF",
    fifaRank: 26,
    wcAppearances: 6,
    bestResult: "16강 (1994, 1998, 2014)",
    continent: "아프리카",
    capital: "아부자",
    population: "약 2억 2,300만",
    languages: "영어",
  },
  GHA: {
    confederation: "CAF",
    fifaRank: 73,
    wcAppearances: 5,
    bestResult: "8강 (2010)",
    continent: "아프리카",
    capital: "아크라",
    population: "약 3,400만",
    languages: "영어",
  },
  CMR: {
    confederation: "CAF",
    fifaRank: 44,
    wcAppearances: 8,
    bestResult: "8강 (1990)",
    continent: "아프리카",
    capital: "야운데",
    population: "약 2,800만",
    languages: "프랑스어 · 영어",
  },
  CIV: {
    confederation: "CAF",
    fifaRank: 33,
    wcAppearances: 4,
    bestResult: "조별리그",
    continent: "아프리카",
    capital: "야무수크로",
    population: "약 3,100만",
    languages: "프랑스어",
  },
  RSA: {
    confederation: "CAF",
    fifaRank: 60,
    wcAppearances: 4,
    bestResult: "조별리그",
    continent: "아프리카",
    capital: "프리토리아",
    population: "약 6,300만",
    languages: "영어 외 11개 공용어",
  },
  MLI: {
    confederation: "CAF",
    fifaRank: 55,
    wcAppearances: 0,
    bestResult: "본선 진출 경험 없음",
    continent: "아프리카",
    capital: "바마코",
    population: "약 2,400만",
    languages: "프랑스어",
  },
  CPV: {
    confederation: "CAF",
    fifaRank: 67,
    wcAppearances: 1,
    bestResult: "첫 본선 진출",
    continent: "아프리카",
    capital: "프라이아",
    population: "약 52만",
    languages: "포르투갈어",
  },
  COD: {
    confederation: "CAF",
    fifaRank: 46,
    wcAppearances: 2,
    bestResult: "조별리그 (1974 · 자이르)",
    continent: "아프리카",
    capital: "킨샤사",
    population: "약 1억 600만",
    languages: "프랑스어",
  },

  // ── OFC (오세아니아) ────────────────────────────────────────
  NZL: {
    confederation: "OFC",
    fifaRank: 85,
    wcAppearances: 3,
    bestResult: "조별리그 (1982, 2010)",
    continent: "오세아니아",
    capital: "웰링턴",
    population: "약 520만",
    languages: "영어 · 마오리어",
  },
};

// Returns the country detail for a given football-data tla, or null when not catalogued.
export function countryDetailFromTla(tla?: string | null): CountryDetail | null {
  if (!tla) return null;
  return COUNTRY_DETAIL_BY_TLA[tla.toUpperCase()] ?? null;
}
